name: jamesparton
favicon: null
layout_spectrum: 0.8312825744505972
typography_spectrum: 0.8662356303539127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7830563851166517
  lightness: 0.9239944922737777
  saturation: 0.11790330475196242
  rhythmicContrast: 0.4507223102264106
purpose: []
